version: 2
jobs:
   build:
     docker:
       - image: circleci/openjdk:latest
     steps:
       - checkout
       - run: echo "hello world"
       - run: wget -q https://dl.bintray.com/sbt/debian/sbt-0.13.15.deb
       - run: sudo dpkg -i sbt-0.13.15.deb