version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - run: wget -q https://dl.bintray.com/sbt/debian/sbt-0.13.15.deb
      - run: sudo dpkg -i sbt-0.13.15.deb
      - run: sbt compile
  test:
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - run: wget -q https://dl.bintray.com/sbt/debian/sbt-0.13.15.deb
      - run: sudo dpkg -i sbt-0.13.15.deb
      - run: sbt test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
        - build